export enum PageType {
  HOME = 'HOME',
  USER = 'USER',
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  ADMIN = 'ADMIN',
  LOGOUT = 'LOGOUT',
  ADMIN_USERS = 'ADMIN_USERS',
  ADMIN_PAYMENTS = 'ADMIN_PAYMENTS',
  ADMIN_ACCOUNTS = 'ADMIN_ACCOUNTS',
  ADMIN_WITHDRAWALS = 'ADMIN_WITHDRAWALS',
}

export const ADMIN_PAGES = [
  PageType.ADMIN,
  PageType.ADMIN_USERS,
  PageType.ADMIN_PAYMENTS,
  PageType.ADMIN_ACCOUNTS,
  PageType.ADMIN_WITHDRAWALS,
];
