export enum PageType {
  HOME = 'HOME',
  USER = 'USER',
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  ADMIN = 'ADMIN',
  LOGOUT = 'LOGOUT',
  ADMIN_USERS = 'ADMIN_USERS',
  ADMIN_PAYMENTS = 'ADMIN_PAYMENTS',
  ADMIN_ACCOUNTS = 'ADMIN_ACCOUNTS',
  ADMIN_WITHDRAWALS = 'ADMIN_WITHDRAWALS',
}
