export enum StylePrefix {
  BADGE = 'badge',
  GENERATE_ACCOUNT_DIALOG = 'generate-account-dialog',
  INPUT_COMPONENT = 'input-component',
  INTERACTABLE_COMPONENT = 'interactable-component',
  SELECT_COMPONENT = 'select-component',
  ADMIN_AUTHORIZE_PAGE = 'admin-authorize-page',
  ADMIN_PAGE = 'admin-page',
  ACCOUNTS_CARD = 'accounts-card',
  CASHAPP_FORM = 'cashapp-form',
  CASHAPP_ACCOUNT_CARD = 'cashapp-account-card',
  CHANGE_HANDLE_FORM = 'change-handle-form',
  PAYMENTS_TABLE = 'payments-table',
  USER_PAYMENTS_TABLE = 'user-payments-table',
  APP_STORE_BUTTONS_DIALOG = 'app-store-buttons-dialog',
  DEPOSIT_DIALOG = 'deposit-dialog',
  PAYMENT_IDENTIFIER_INPUT = 'payment-identifier-input',
  PLAY_NOW_DIALOG = 'play-now-dialog',
  SUCCESS_DIALOG = 'success-dialog',
  PLAY_CREATE_BOX = 'play-create-box',
  HEADER_V2 = 'header-v2',
}
