query GetAccounts($input: GetAllAccountsInput) {
  getAllAccounts(input: $input) {
    id
    updatedAt
    email
    balance
    canWithdrawal
    canAcceptDeposits
    dailyWithdrawals
    weeklyWithdrawals
  }
}