mutation SignUp($input: SignUpInput!) {
  signUp(input: $input) {
    success
    session {
      provider_token
      provider_refresh_token
      access_token
      refresh_token
      expires_in
      expires_at
      token_type
    }
    user {
      ...User
    }
  }
}