query GetProcessedUserPayments($input: GetUserPaymentsInput = { processed: true }) {
  getUserPayments(input: $input) {
    ...UserPaymentFragment
    createdAt
  }
}

query GetPendingUserPayments($input: GetUserPaymentsInput = { processed: false }) {
  getUserPayments(input: $input) {
    ...UserPaymentFragment
    createdAt
  }
}
