mutation UpdateWithdrawalRequestStatus($input: UpdateWithdrawalRequestStatusInput!) {
  updateWithdrawalRequestStatus(input: $input) {
    success
    withdrawalRequest {
      ...WithdrawalRequestFragment
    }
  }
}
