FROM node:16-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN apk add findutils-locate
RUN yarn install

FROM node:16-alpine AS prod

WORKDIR /app
COPY --from=builder /app/ /app/
COPY . .
RUN apk add bash
WORKDIR /app/api
RUN yarn add typescript
RUN yarn build

EXPOSE 8000

CMD ["yarn", "start"]