FROM node:16-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install

FROM node:16-alpine AS prod

WORKDIR /app
COPY --from=builder /app/ /app/
COPY . .
RUN yarn build:api

EXPOSE 8000

CMD ["yarn", "start"]